---
title: "Setting a strict clock with a constant rate"
author: "Richel Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Setting a strict clock with a constant rate}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In this vignette, I explore to set a fixed clock with
a known number of nucleotide substitutions.

```{r}
library(babette)
simple_names <- names(
  bbt_run(
    fasta_filenames = get_babette_path("anthus_aco_sub.fas"),
    clock_models = create_strict_clock_model(),
    mcmc = create_mcmc(
      chain_length = 2000, 
      store_every = 1000
    )
  )$estimates
)
hard_names <- names(
  bbt_run(
    fasta_filenames = get_babette_path("anthus_aco.fas"),
    clock_models = create_strict_clock_model(
      clock_rate_param = create_clock_rate_param(
        value = 10.0, estimate = FALSE
      ),
      clock_rate_distr = create_normal_distr(
        mean = create_mean_param(
          value = 10.0, 
          estimate = FALSE
        ),
        sigma = create_sigma_param(
          value = 0.01, 
          estimate = FALSE
        )
      )
    ),
    mcmc = create_mcmc(
      chain_length = 2000, 
      store_every = 1000
    )
  )$estimates
)
testit::assert(simple_names == hard_names)
```
