---
title: "nLTT statistics when changing speciation completion rate"
output: pdf_document
---

Speciation long:

```{r}
results <- list()
params_a <- raket::create_params(
  speciation_initiation_rate = 0.2,
  speciation_completion_rate = 5.0,
  extinction_rate = 0.1,
  crown_age = 15,
  crown_age_sigma = 0.01,
  sampling_method = "youngest",
  mutation_rate = 1.0,
  sequence_length = 100,
  mcmc_length = 300000,
  tree_sim_rng_seed = 43,
  alignment_rng_seed = 43,
  beast2_rng_seed = 44
)
results$a <- raket::run(parameters = params_a) 
ape::plot.phylo(results$a$species_tree)
results$a$nltts_diff <- nLTT::nltts_diff(tree = results$a$species_tree, results$a$trees)
tracerer::calc_ess(results$a$estimates$posterior, sample_interval = 1000)
```

Short:

```{r}
params_b <- params_a
params_b$speciation_completion_rate <- 1000000.0
results$b <- raket::run(parameters = params_b) 
ape::plot.phylo(results$b$species_tree)
results$b$nltts_diff <- nLTT::nltts_diff(tree = results$b$species_tree, results$b$trees)
tracerer::calc_ess(results$b$estimates$posterior, sample_interval = 1000)
```

Plot:

```{r}
df <- data.frame(
  sim = c(
    rep("a", times = length(results$a$nltts_diff)), 
    rep("b", times = length(results$b$nltts_diff))
  ),
  nltts = c(results$a$nltts_diff, results$b$nltts_diff)
)
ggplot2::ggplot(
  data = df,
  ggplot2::aes(x = nltts, fill = sim)
) + ggplot2::geom_histogram(alpha = 0.5, position = "identity", binwidth = 0.01)
```

