---
title: "R Notebook"
output: pdf_document
---

```{r}
library(pirouette)
```


```{r}
set.seed(42)
crown_age <- 15
true_phylogeny <- TreeSim::sim.bd.age(age = crown_age, numbsim = 1, lambda = 0.2, mu = 0.02, frac = 1.0, complete = FALSE)[[1]]
ape::plot.phylo(true_phylogeny)
```

```{r}
true_alignment <- pirouette::sim_alignment(
  true_phylogeny, 
  sequence_length = 1000,
  mutation_rate = 0.01
)
image(true_alignment)
```
  
```{r}
fasta_filename <- tempfile(fileext = ".fas")
phangorn::write.phyDat(
  true_alignment,
  file = fasta_filename,
  format = "fasta"
)
```

```{r}
mcmc <- beautier::create_mcmc(chain_length = 100000)
mrca_prior <- beautier::create_mrca_prior(
  alignment_id = beautier::get_alignment_id(fasta_filename),
  taxa_names = beautier::get_taxa_names(fasta_filename),
  is_monophyletic = TRUE,
  mrca_distr = beautier::create_normal_distr(
    mean = beautier::create_mean_param(value = crown_age),
    sigma = beautier::create_sigma_param(value = 0.01)
  )
)
out_yule <- babette::run(
  fasta_filenames = fasta_filename,
  tree_priors = create_yule_tree_prior(),
  mrca_priors = mrca_prior,
  mcmc = mcmc
)
out_bd <- babette::run(
  fasta_filenames = fasta_filename,
  tree_priors = create_bd_tree_prior(),
  mrca_priors = mrca_prior,
  mcmc = mcmc
)
out_ccp <- babette::run(
  fasta_filenames = fasta_filename,
  tree_priors = create_ccp_tree_prior(),
  mrca_priors = mrca_prior,
  mcmc = mcmc
)
```

```{r}
names(out_yule)[1] <- "trees"
names(out_bd)[1] <- "trees"
names(out_ccp)[1] <- "trees"
n <- length(out_yule$trees)
trees <- c(out_yule$trees, out_bd$trees, out_ccp$trees)
colors <- rep(c("red", "green", "blue"), each = n)
testit::assert(length(trees) == length(colors))
babette::plot_densitree(phylos = out_yule$trees, concensus = true_phylogeny, col = "red", width = 1, alpha = 10 / n)
babette::plot_densitree(phylos = out_bd$trees, concensus = true_phylogeny, col = "green", width = 1, alpha = 10 / n)
babette::plot_densitree(phylos = out_ccp$trees, concensus = true_phylogeny, col = "blue", width = 1, alpha = 10 / n)

babette::plot_densitree(phylos = trees, concensus = true_phylogeny, col = colors, width = 1, alpha = 10 / n)
```