#!/bin/bash
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=analyse
#SBATCH --output=analyse.log
module load R/3.3.1-foss-2016a
folder_name=$1
output_filename=median_nltts.csv
cmd="flechette::calc_median_nltts(\""$folder_name"\",\""$output_filename"\")"
echo $cmd
Rscript -e $cmd
