#!/bin/bash
# Script to install flechette and its dependencies
# on the Peregrine computer cluster 
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=install_flechette
#SBATCH --output=install_flechette.log
module load R/3.3.1-foss-2016a
Rscript -e 'devtools::install_github("KlausVigo/phangorn")'
Rscript -e 'devtools::install_github("richelbilderbeek/nLTT")'
Rscript -e 'devtools::install_github("richelbilderbeek/beautier")'
Rscript -e 'devtools::install_github("richelbilderbeek/beastier")'
Rscript -e 'devtools::install_github("richelbilderbeek/tracerer")'
Rscript -e 'devtools::install_github("richelbilderbeek/babette")'
Rscript -e 'devtools::install_github("richelbilderbeek/flechette")'
