#!/bin/bash

cd ..
git checkout master
git merge develop
git push
git checkout develop
cd ..

cd beautier
git checkout master
git merge develop
git push
git checkout develop
cd ..

cd beastier
git checkout master
git merge develop
git push
git checkout develop
cd ..

cd flechette
git checkout master
git merge develop
git push
git checkout develop
cd ..

cd pirouette
git checkout master
git merge develop
git push
git checkout develop
cd ..

cd tracerer
git checkout master
git merge develop
git push
git checkout develop
cd ..
