#!/bin/bash
# Script to install flechette on the Peregrine computer cluster
# Peregrine directives:
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=process_1
#SBATCH --output=process_1_%j.log
module load R/3.3.1-foss-2016a
Rscript -e 'flechette::create_output_file("$1","out_$1")'
