#!/bin/bash

# Push all GitHubs under flechette

cd ..
git add --all :/
git commit -m "flechette update"
git push
cd ..

cd beautier
git add --all :/
git commit -m "flechette update"
git push
cd ..

cd beastier
git add --all :/
git commit -m "flechette update"
git push
cd ..

cd tracerer
git add --all :/
git commit -m "flechette update"
git push
cd ..
